
version: "3.3"

services:
  nginx:
      image: ccr.ccs.tencentyun.com/cleocn/nginx:1.9 #cleocn/nginx:1.9
      ports:
          - 3080:80
      volumes:
        - /data/h5/src:/var/www/app/web
        - /data/h5/Uploads:/var/www/app/web/Uploads
        - /data/h5/conf:/var/www/app/web/Application/Common/Conf
        # - /Users/ljx/code/eqx12.9/nginx.conf:/etc/nginx/conf.d/default.conf
        # - vendor: /vendor
      environment:
          DOCUMENT_ROOT: /var/www/app/web
          INDEX_FILE: index.php
          PHP_FPM_SOCKET: php.local:9000
      networks:
        - default

  php:
      image: yappabe/php:5.3
      ports:
          - 9000:9000
      volumes:
          - /data/h5/src:/var/www/app/web
          - /data/h5/phptmp:/var/www/app/web/Application/Runtime
          - /data/h5/Uploads:/var/www/app/web/Uploads
          - /data/h5/conf:/var/www/app/web/Application/Common/Conf
      networks:
        default:
          aliases:
            - php.local
